import { createClient } from '@supabase/supabase-js';

function getSupabaseClient() {
    return createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL,
        process.env.SUPABASE_SERVICE_ROLE_KEY
    );
}

export async function POST(request) {
    try {
        const { name, description, teacherId } = await request.json();

        if (!name || !teacherId) {
            return Response.json({ error: 'Name and teacher ID required' }, { status: 400 });
        }

        // Create classroom (invite code auto-generated by trigger)
        const supabase = getSupabaseClient();
        const { data: classroom, error } = await supabase
            .from('classrooms')
            .insert({
                name,
                description,
                teacher_id: teacherId
            })
            .select()
            .single();

        if (error) {
            console.error('Error creating classroom:', error);
            return Response.json({ error: error.message }, { status: 500 });
        }

        return Response.json({ classroom }, { status: 201 });
    } catch (error) {
        console.error('Error:', error);
        return Response.json({ error: 'Internal server error' }, { status: 500 });
    }
}

export async function GET(request) {
    try {
        const { searchParams } = new URL(request.url);
        const teacherId = searchParams.get('teacherId');

        if (!teacherId) {
            return Response.json({ error: 'Teacher ID required' }, { status: 400 });
        }

        // Get all classrooms for this teacher
        const supabase = getSupabaseClient();
        const { data: classrooms, error } = await supabase
            .from('classrooms')
            .select(`
        *,
        classroom_enrollments(count)
      `)
            .eq('teacher_id', teacherId)
            .eq('is_active', true)
            .order('created_at', { ascending: false });

        if (error) {
            console.error('Error fetching classrooms:', error);
            return Response.json({ error: error.message }, { status: 500 });
        }

        return Response.json({ classrooms });
    } catch (error) {
        console.error('Error:', error);
        return Response.json({ error: 'Internal server error' }, { status: 500 });
    }
}

export async function DELETE(request) {
    try {
        const { searchParams } = new URL(request.url);
        const classroomId = searchParams.get('id');

        if (!classroomId) {
            return Response.json({ error: 'Classroom ID required' }, { status: 400 });
        }

        // Soft delete
        const supabase = getSupabaseClient();
        const { error } = await supabase
            .from('classrooms')
            .update({ is_active: false })
            .eq('id', classroomId);

        if (error) {
            console.error('Error deleting classroom:', error);
            return Response.json({ error: error.message }, { status: 500 });
        }

        return Response.json({ success: true });
    } catch (error) {
        console.error('Error:', error);
        return Response.json({ error: 'Internal server error' }, { status: 500 });
    }
}
